# Generated by Django 2.2 on 2019-06-07 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_choice_choice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct',
            field=models.IntegerField(default=0),
        ),
    ]
