# Generated by Django 2.1 on 2019-06-19 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_auto_20190619_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice1',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='testapp.Quiz1'),
        ),
    ]
