# Generated by Django 2.1 on 2019-06-19 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='quiz1',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='quiz1',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='quiz1',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='quiz1',
            name='choice4',
        ),
        migrations.RemoveField(
            model_name='quiz2',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='quiz2',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='quiz2',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='quiz2',
            name='choice4',
        ),
        migrations.AddField(
            model_name='choice1',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Quiz1'),
        ),
    ]
