# Generated by Django 2.1 on 2019-06-19 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_choice2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz1',
            old_name='question',
            new_name='question_text',
        ),
    ]
