# Generated by Django 2.1 on 2019-06-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_auto_20190612_1505'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AddField(
            model_name='users',
            name='user',
            field=models.CharField(default='thirumalai', max_length=100, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
